# Generated by Django 2.1.2 on 2018-10-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('cmc_id', models.IntegerField()),
                ('explorer', models.CharField(max_length=200)),
                ('based_on_blockchain', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('reddit', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Token_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_usd_upd_date', models.DateTimeField()),
                ('cmc_usd_price', models.FloatField()),
                ('cmc_btc_upd_date', models.DateTimeField()),
                ('cmc_btc_price', models.FloatField()),
                ('Token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokensDB.Token')),
            ],
        ),
    ]
