# Generated by Django 2.1.2 on 2018-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='based_on_blockchain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='circulating_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='explorer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='max_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='reddit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='total_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='token_price',
            name='cmc_btc_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='token_price',
            name='cmc_btc_upd_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='token_price',
            name='cmc_usd_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='token_price',
            name='cmc_usd_upd_date',
            field=models.DateTimeField(null=True),
        ),
    ]
