# Generated by Django 2.1.2 on 2018-10-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0004_auto_20181008_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='circulating_supply',
            new_name='curculating_supply',
        ),
    ]
