# Generated by Django 2.1.2 on 2018-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0005_auto_20181010_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='curculating_supply',
        ),
        migrations.AddField(
            model_name='token',
            name='circulating_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
