# Generated by Django 2.1.2 on 2018-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0008_auto_20181010_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='smart_contract_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
