# Generated by Django 2.1.2 on 2018-10-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0009_token_smart_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_price',
            name='cmc_btc_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token_price',
            name='cmc_btc_upd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
