# Generated by Django 2.1.2 on 2018-10-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0010_auto_20181011_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_price',
            old_name='Token',
            new_name='token',
        ),
    ]
