# Generated by Django 2.1.2 on 2018-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokensDB', '0011_auto_20181016_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='based_on_blockchain',
        ),
        migrations.AddField(
            model_name='token',
            name='blockchain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
